version: "3.8"
services:
  db:
    image: docker.io/library/postgres:15
    container_name: postgres-sonic
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  meilisearch:
    image: getmeili/meilisearch:v1.44.0
    container_name: meilisearch-sonic
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_MASTER_KEY}
      MEILI_ENV: "development"
    volumes:
      - meilisearch_data:/meili_data
    restart: always

volumes:
  postgres_data:
  meilisearch_data:
